package com.mycompany.buat_apk.frames;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.ArrayList;
import java.util.List;

import com.mycompany.buat_apk.domains.entities.categories.Category;
import com.mycompany.buat_apk.domains.entities.products.CreateProduct;
import com.mycompany.buat_apk.domains.entities.products.ProductWithStocks;
import com.mycompany.buat_apk.domains.frames.ComboCategory;
import com.mycompany.buat_apk.registry.AppContextRegistry;
import com.mycompany.buat_apk.registry.ServiceRegistry;
import com.mycompany.buat_apk.services.CategoryService;
import com.mycompany.buat_apk.services.ProductService;

/**
 *
 * @author najwa amanda
 */
public class frame_editProduk extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_editProduk.class.getName());
    private java.io.File photo = null;

    private MainFrame parent;

    private String name;
    private String description;
    private int stock;
    private Long price;
    private Long category_id;

    private AppContextRegistry context;

    private final ProductService productService;
    private final CategoryService categoryService;

    /**
     * Creates new form frame_produk
     */
    public frame_editProduk(MainFrame parent) {
        this.parent = parent;

        ServiceRegistry serviceRegistry = ServiceRegistry.getInstance();

        this.productService = serviceRegistry.productService;
        this.categoryService = serviceRegistry.categoryService;

        AppContextRegistry context = AppContextRegistry.getInstance();
        this.context = context;
        
        for (ProductWithStocks e : this.productService.getAllProductsWithStocks()) {
           System.out.println(e.getImageFile().getAbsolutePath()); 
        }

        initComponents();

        loadCategories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descFieldedit = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        categoryFieldedit = new javax.swing.JComboBox<>();
        photoField = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Edit Produk");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama Produk");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Harga Satuan (Rp)");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Deskripsi");

        descFieldedit.setColumns(20);
        descFieldedit.setRows(5);
        jScrollPane1.setViewportView(descFieldedit);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Kategori");

        photoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Perbarui informasi produk");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Edit Informasi Produk");

        jButton1.setBackground(new java.awt.Color(246, 246, 246));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jButton1.setText("<");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Choose Image");

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Simpan Perubahan");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton4.setText("Batal");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photoField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryFieldedit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1)
                            .addComponent(jTextField2))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryFieldedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void clearForm() {
        // nameFieldedit.setText("");
        // priceFieldedit.setText("");
        // stockField.setText("");
        // descFieldedit.setText("");
        //
        // clearImage();
        //
        // this.name = "";
        // this.description = "";
        // this.category_id = null;
        // this.photo = null;
        // this.price = null;
        // this.stock = 0;
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {

//GEN-FIRST:event_saveButtonActionPerformed
        // String name = nameFieldedit.getText();
        // String desc = nameFieldedit.getText();

        // if (name.equals("") || desc.equals("")) {
        //     javax.swing.JOptionPane.showMessageDialog(this, 
        //             "Please enter the correct name and description.", 
        //             "Input Error", 
        //             javax.swing.JOptionPane.ERROR_MESSAGE);
        //
        //     return;
        // }

        // this.name = name;
        // this.description = desc;
        //
        // ComboCategory selectedCategory = (ComboCategory) categoryFieldedit.getSelectedItem();
        //
        // if(selectedCategory == null) {
        //     javax.swing.JOptionPane.showMessageDialog(this, 
        //             "Please input the right category.", 
        //             "Input Error", 
        //             javax.swing.JOptionPane.ERROR_MESSAGE);
        //     return;
        // }
        //
        // this.category_id = selectedCategory.id;
        //
        // try {
        //     String stockText = stockField.getText();
        //     String priceText = priceFieldedit.getText();
        //
        //     int stock = Integer.parseInt(stockText);
        //     Long price = Long.parseLong(priceText);
        //
        //     if (stock < 0 || price < 0) {
        //         throw new IllegalArgumentException("Values cannot be negative.");
        //     }
        //
        //
        //     this.stock = stock;
        //     this.price = price;
        // } catch (NumberFormatException e) {
        //     javax.swing.JOptionPane.showMessageDialog(this, 
        //             "Please enter valid numbers for Stock and Price.", 
        //             "Input Error", 
        //             javax.swing.JOptionPane.ERROR_MESSAGE);
        //
        //     return;
        //
        // } catch (IllegalArgumentException e) {
        //     javax.swing.JOptionPane.showMessageDialog(this, 
        //             e.getMessage(), 
        //             "Input Error", 
        //             javax.swing.JOptionPane.WARNING_MESSAGE);
        //     return;
        // }
        //
        // try {
        //
        //     if (this.photo != null) {
        //         java.io.File targetDir = new java.io.File("storage/images");
        //         if (!targetDir.exists()) targetDir.mkdirs();
        //
        //         java.io.File targetFile = new java.io.File(targetDir, this.photo.getName());
        //
        //         java.nio.file.Files.copy(
        //                 this.photo.toPath(), 
        //                 targetFile.toPath(), 
        //                 java.nio.file.StandardCopyOption.REPLACE_EXISTING
        //                 );
        //
        //         System.out.println("Image saved to: " + targetFile.getPath());
        //     }
        //
        //
        // } catch (Exception e) {
        //     javax.swing.JOptionPane.showMessageDialog(this, "Error saving: " + e.getMessage());
        //     return;
        // }
        //
        // CreateProduct createProductData = new CreateProduct();
        // createProductData.setName(this.name);
        // createProductData.setImage(this.photo.getName());
        // createProductData.setQuantity(this.stock);
        // createProductData.setCategoryId(this.category_id);
        // createProductData.setDescription(this.description);
        // createProductData.setPrice(this.price);
        //
        // System.out.println("name: " + this.name);
        // System.out.println("description: " + this.description);
        // System.out.print("stock: ");
        // System.out.println(this.stock);
        // System.out.print("price: ");
        // System.out.println(this.price);
        // System.out.print("category_id: ");
        // System.out.println(this.category_id);
        // System.out.print("photo: ");
        // System.out.println(this.photo.getName());
        //
        // this.productService.createProduct(this.context.getActiveUser().getId(), createProductData);
        //
        //
        // clearForm();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void displayImage(String path) {
        try {
            int width = photoField.getWidth();
            int height = photoField.getHeight();

            if (width == 0 || height == 0) {
                width = 150;
                height = 150;
            }

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);

            java.awt.Image img = icon.getImage();
            java.awt.Image scaledImg = img.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);

            photoField.setIcon(new javax.swing.ImageIcon(scaledImg));

            photoField.repaint();
            photoField.revalidate();

        } catch (Exception e) {
            System.err.println("Error displaying image: " + e.getMessage());
        }
    }

    private void clearImage() {
        photoField.setIcon(null);

        this.photo = null;
        photoField.repaint();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        MainFrame mf = new MainFrame();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frame_editProduk(mf).setVisible(true));
    }

    public void loadCategories() {
        try {
            List<Category> categoryList = this.categoryService.getAllCategories();

            List<ComboCategory> comboCategoryList = new ArrayList<>();

            for (Category c : categoryList) {
                comboCategoryList.add(new ComboCategory(c.getId(), c.getName())); 
            }

            ComboCategory[] comboCategoryArray = comboCategoryList.toArray(new ComboCategory[0]);

            categoryFieldedit.setModel(new javax.swing.DefaultComboBoxModel<>(comboCategoryArray));

        } catch (Exception e) {
            // Standard error handling for Jakarta-based SWE projects
            System.err.println("Error loading categories: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error: Could not retrieve categories.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ComboCategory> categoryFieldedit;
    private javax.swing.JTextArea descFieldedit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel photoField;
    // End of variables declaration//GEN-END:variables
}
