/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.buat_apk.frames;

import com.mycompany.buat_apk.domains.entities.customers.Customer;
import com.mycompany.buat_apk.domains.entities.customers.UpdateCustomer;
import com.mycompany.buat_apk.registry.ServiceRegistry;
import com.mycompany.buat_apk.services.CustomerService;

/**
 *
 * @author najwa amanda
 */
public class frame_customerDetail extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_customerDetail.class.getName());
    private MainFrame parent;
    private CustomerService service;
    private Long selectedId;

    /**
     * Creates new form Frame_costumer
     */
    public frame_customerDetail(MainFrame parent) {
        initComponents();
        this.parent=parent;

        ServiceRegistry serviceRegistry = ServiceRegistry.getInstance();
        this.service = serviceRegistry.customerService;
    }

    public void loadFormData(Long id) {
        this.selectedId = id;
        if (this.selectedId == null) {
            return;
        }

        try {
            com.mycompany.buat_apk.domains.entities.customers.Customer customer = this.service.getCustomerById(id);

            if (customer != null) {
                jLabel1.setText("CUSTOMER DETAILS (ID: " + customer.getId() + ")");

                nameField.setText(customer.getName());
                phoneField.setText(customer.getPhone());
                domisiliField.setText(customer.getSubdistrict());

                if (customer.getDob() != null) {
                    java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd-MM-yyyy");
                    dobField.setText(dateFormat.format(customer.getDob()));
                } else {
                    dobField.setText("");
                }

                // Optional: If you want to list context data in the underlying table:

            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Data pelanggan tidak ditemukan.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                this.parent.goTo("CUSTOMER_LIST");
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal memuat form data pelanggan", ex);
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Terjadi kesalahan saat memuat data: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        domisiliField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dobField = new javax.swing.JFormattedTextField();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("DETAIL CUSTOMER");

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backBtn.setText("<");
        backBtn.addActionListener(this::backBtnActionPerformed);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Customer Name               :");

        jLabel6.setText("Phone Number                 :");

        jLabel4.setText("Domicile                           :");

        resetBtn.setText("Reset");
        resetBtn.addActionListener(this::resetBtnActionPerformed);

        saveBtn.setBackground(new java.awt.Color(0, 51, 255));
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(this::saveBtnActionPerformed);

        jLabel5.setText("Date of Birth                     :");

        dobField.addActionListener(this::dobFieldActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                                .addComponent(nameField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(domisiliField))
                            .addComponent(dobField))))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(domisiliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        deleteBtn.setBackground(new java.awt.Color(255, 204, 204));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 51, 51));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(deleteBtn)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if (this.selectedId == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Aksi tidak valid: Tidak ada data pelanggan yang dipilih untuk diperbarui.", 
                    "Kesalahan Konten", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            this.parent.goTo("CUSTOMER_LIST");
            return;
        }

        String name = nameField.getText().trim();
        String phone = phoneField.getText().trim();
        String subdistrict = domisiliField.getText().trim();
        String dobString = dobField.getText().trim(); 

        if (name.isEmpty() || phone.isEmpty() || subdistrict.isEmpty() || dobString.contains("_") || dobString.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Semua kolom (Nama, No. Telepon, Domisili, dan Tanggal Lahir) harus diisi dengan lengkap!", 
                    "Validasi Gagal", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.util.Date dobDate = null;
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd-MM-yyyy");
        dateFormat.setLenient(false); 

        try {
            dobDate = dateFormat.parse(dobString);
        } catch (java.text.ParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Format tanggal lahir tidak valid! Gunakan susunan DD-MM-YYYY.", 
                    "Validasi Gagal", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        UpdateCustomer updateData = new UpdateCustomer(
            this.selectedId,
            name,
            dobDate,
            subdistrict,
            phone
        );

        boolean success = this.service.updateCustomer(updateData);

        if (success) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Data pelanggan berhasil diperbarui!", 
                    "Sukses", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            this.parent.goTo("CUSTOMER_LIST");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Gagal memperbarui data pelanggan. Pastikan ID valid di database.", 
                    "Kesalahan Sistem", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        this.clearForm();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.parent.goTo("CUSTOMER_LIST");
    }//GEN-LAST:event_backBtnActionPerformed

    private void dobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobFieldActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
                                                                           // 1. Guard clause: Ensure there is actually a customer record loaded
        if (this.selectedId == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Aksi tidak valid: Tidak ada data pelanggan yang dipilih untuk dihapus.", 
                    "Kesalahan Konten", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Safety Confirmation Dialog
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin menghapus pelanggan ini secara permanen?", 
                "Konfirmasi Hapus", 
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
                );

        // 3. Process deletion if confirmed
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            boolean success = this.service.deleteCustomerById(this.selectedId);

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Data pelanggan berhasil dihapus.", 
                        "Sukses", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);

                // Clear state and force view back to the updated listing grid
                this.selectedId = null;
                this.clearForm();
                this.parent.goTo("CUSTOMER_LIST");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Gagal menghapus data pelanggan. Silakan periksa log sistem.", 
                        "Kesalahan Sistem", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearForm() {
        loadFormData(selectedId);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        MainFrame mf = new MainFrame();
        java.awt.EventQueue.invokeLater(() -> new frame_customerDetail(mf).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JFormattedTextField dobField;
    private javax.swing.JTextField domisiliField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
