/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.buat_apk.frames;

import java.io.File;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.swing.JOptionPane;

import com.mycompany.buat_apk.config.AppConfig;
import com.mycompany.buat_apk.domains.entities.stocks.DailyTransactionSummary;
import com.mycompany.buat_apk.registry.ServiceRegistry;
import com.mycompany.buat_apk.services.StockService;

import io.github.cdimascio.dotenv.Dotenv;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author rahim
 */
public class frame_test extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_test.class.getName());

    private StockService stockService;

    private static final String[] MONTHS = {
        "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
    };

    public frame_test() {
        Dotenv dotenv = Dotenv.load();
        AppConfig.setEnvironmentVariable(dotenv);

        ServiceRegistry services = ServiceRegistry.getInstance();
        this.stockService = services.stockService;
        initComponents();
        populateYearCombo();
    }

    private void populateYearCombo() {
        int currentYear = LocalDate.now().getYear();
        yearCombo.removeAllItems();
        for (int y = currentYear - 2; y <= currentYear + 3; y++) {
            yearCombo.addItem(y);
        }
        yearCombo.setSelectedItem(currentYear);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        yearCombo = new javax.swing.JComboBox<>();
        printButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cetak Laporan Transaksi");
        getContentPane().setLayout(null);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 16));
        titleLabel.setText("Cetak Laporan Transaksi");
        getContentPane().add(titleLabel);
        titleLabel.setBounds(100, 20, 220, 25);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel1.setText("Bulan:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 50, 25);

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(MONTHS));
        monthCombo.setSelectedIndex(LocalDate.now().getMonthValue() - 1);
        getContentPane().add(monthCombo);
        monthCombo.setBounds(80, 68, 150, 28);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12));
        jLabel2.setText("Tahun:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 70, 50, 25);

        getContentPane().add(yearCombo);
        yearCombo.setBounds(290, 68, 80, 28);

        printButton.setFont(new java.awt.Font("Segoe UI", 1, 14));
        printButton.setText("Cetak");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printButton);
        printButton.setBounds(150, 120, 100, 35);

        setSize(new java.awt.Dimension(400, 200));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int month = monthCombo.getSelectedIndex() + 1;
            int year = (int) yearCombo.getSelectedItem();
            YearMonth ym = YearMonth.of(year, month);

            List<DailyTransactionSummary> data = stockService.getDailySummaryByMonth(ym);

            Map<String, Object> params = new HashMap<>();
            params.put("periode",
                DateTimeFormatter.ofPattern("MMMM yyyy", Locale.of("id", "ID"))
                    .format(LocalDate.of(year, month, 1)));

            InputStream jrxml = getClass().getResourceAsStream("/reports/laporan_transaksi_bulanan.jrxml");
            if (jrxml == null) {
                JOptionPane.showMessageDialog(this,
                    "Template JRXML tidak ditemukan di classpath (/reports/laporan_transaksi_bulanan.jrxml)");
                return;
            }

            JasperReport report = JasperCompileManager.compileReport(jrxml);
            JasperPrint print = JasperFillManager.fillReport(report, params,
                new JRBeanCollectionDataSource(data));

            String fileName = String.format("laporan_transaksi_%d_%02d.pdf", year, month);
            String outPath = System.getProperty("user.dir") + File.separator + fileName;
            JasperExportManager.exportReportToPdfFile(print, outPath);

            JOptionPane.showMessageDialog(this, "PDF tersimpan di:\n" + outPath);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal export PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new frame_test().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JComboBox<Integer> yearCombo;
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables
}
