/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.buat_apk.frames;

import com.mycompany.buat_apk.domains.entities.customers.CustomerSummary;
import com.mycompany.buat_apk.domains.entities.products.ProductWithStocks;
import com.mycompany.buat_apk.domains.entities.stocks.DailyTransactionSummary;
import com.mycompany.buat_apk.domains.entities.stocks.ProductTransactionSummary;
import com.mycompany.buat_apk.registry.ServiceRegistry;
import com.mycompany.buat_apk.services.CustomerService;
import com.mycompany.buat_apk.services.ProductService;
import com.mycompany.buat_apk.services.StockService;

import java.awt.Desktop;
import java.io.File;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.swing.JOptionPane;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author rahim
 */
public class frame_print extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_print.class.getName());

    private static final String[] MONTHS = {
        "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
    };

    private MainFrame parent;

    private StockService stockService;
    private ProductService productService;
    private CustomerService customerService;

    /**
     * Creates new form frame_print
     */
    public frame_print(MainFrame parent) {
        initComponents();
        this.parent = parent;

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(MONTHS));
        jComboBox2.setSelectedIndex(java.time.LocalDate.now().getMonthValue() - 1);

        int currentYear = java.time.LocalDate.now().getYear();
        String[] years = new String[currentYear + 4 - (currentYear - 2)];
        for (int i = 0; i < years.length; i++) {
            years[i] = String.valueOf((currentYear - 2) + i);
        }
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(years));
        jComboBox3.setSelectedItem(String.valueOf(currentYear));

        ServiceRegistry registry = ServiceRegistry.getInstance();
        this.stockService = registry.stockService;
        this.productService = registry.productService;
        this.customerService = registry.customerService;

        btnLaporanStock.addActionListener(this::btnLaporanStockActionPerformed);
        btnLaporanCustomer.addActionListener(this::btnLaporanCustomerActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnLaporanNetProduk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnLaporanStock = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnLaporanCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        btnLaporanNetProduk1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(791, 608));
        setMinimumSize(new java.awt.Dimension(791, 608));
        setPreferredSize(new java.awt.Dimension(791, 608));

        btnLaporanNetProduk.setText("Cetak laporan net bulanan");
        btnLaporanNetProduk.addActionListener(this::btnLaporanNetProdukActionPerformed);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Laporan Stok produk");

        btnLaporanStock.setText("Cetak");

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Laporan customer");

        btnLaporanCustomer.setText("Cetak");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel2.setText("Bulan: ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel3.setText("Tahun:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLaporanNetProduk1.setText("Cetak laporan net produk");
        btnLaporanNetProduk1.addActionListener(this::btnLaporanNetProduk1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLaporanCustomer)
                        .addGap(37, 37, 37))
                    .addComponent(jLabel6))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnLaporanStock))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLaporanNetProduk)
                            .addComponent(btnLaporanNetProduk1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnLaporanNetProduk)
                .addGap(18, 18, 18)
                .addComponent(btnLaporanNetProduk1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLaporanStock))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLaporanCustomer)))
                .addGap(101, 101, 101))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String reportsPath(String fileName) {
        File dir = new File(System.getProperty("user.dir"), "reports");
        if (!dir.exists()) {
            dir.mkdirs();
        }
        return new File(dir, fileName).getAbsolutePath();
    }

    private void openPdf(String outPath) {
        if (Desktop.isDesktopSupported()
                && Desktop.getDesktop().isSupported(Desktop.Action.OPEN)) {
            try {
                Desktop.getDesktop().open(new File(outPath));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void btnLaporanNetProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanNetProdukActionPerformed
        try {
            int month = Arrays.asList(MONTHS).indexOf(jComboBox2.getSelectedItem()) + 1;
            int year = Integer.parseInt((String) jComboBox3.getSelectedItem());
            YearMonth ym = YearMonth.of(year, month);

            List<DailyTransactionSummary> data = stockService.getDailySummaryByMonth(ym);

            Map<String, Object> params = new HashMap<>();
            params.put("periode",
                DateTimeFormatter.ofPattern("MMMM yyyy", Locale.of("id", "ID"))
                    .format(LocalDate.of(year, month, 1)));

            InputStream jrxml = getClass().getResourceAsStream("/reports/laporan_transaksi_bulanan.jrxml");
            if (jrxml == null) {
                JOptionPane.showMessageDialog(this,
                    "Template JRXML tidak ditemukan di classpath (/reports/laporan_transaksi_bulanan.jrxml)");
                return;
            }

            JasperReport report = JasperCompileManager.compileReport(jrxml);
            JasperPrint print = JasperFillManager.fillReport(report, params,
                new JRBeanCollectionDataSource(data));

            String fileName = String.format("laporan_transaksi_%d_%02d.pdf", year, month);
            String outPath = reportsPath(fileName);
            JasperExportManager.exportReportToPdfFile(print, outPath);
            openPdf(outPath);

            JOptionPane.showMessageDialog(this, "PDF tersimpan di:\n" + outPath);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal export PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLaporanNetProdukActionPerformed

    private void btnLaporanNetProduk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanNetProduk1ActionPerformed
        try {
            int month = Arrays.asList(MONTHS).indexOf(jComboBox2.getSelectedItem()) + 1;
            int year = Integer.parseInt((String) jComboBox3.getSelectedItem());
            YearMonth ym = YearMonth.of(year, month);

            List<ProductTransactionSummary> data = stockService.getProductSummaryByMonth(ym);

            Map<String, Object> params = new HashMap<>();
            params.put("periode",
                DateTimeFormatter.ofPattern("MMMM yyyy", Locale.of("id", "ID"))
                    .format(LocalDate.of(year, month, 1)));

            InputStream jrxml = getClass().getResourceAsStream("/reports/laporan_transaksi_produk.jrxml");
            if (jrxml == null) {
                JOptionPane.showMessageDialog(this,
                    "Template JRXML tidak ditemukan di classpath (/reports/laporan_transaksi_produk.jrxml)");
                return;
            }

            JasperReport report = JasperCompileManager.compileReport(jrxml);
            JasperPrint print = JasperFillManager.fillReport(report, params,
                new JRBeanCollectionDataSource(data));

            String fileName = String.format("laporan_transaksi_produk_%d_%02d.pdf", year, month);
            String outPath = reportsPath(fileName);
            JasperExportManager.exportReportToPdfFile(print, outPath);
            openPdf(outPath);

            JOptionPane.showMessageDialog(this, "PDF tersimpan di:\n" + outPath);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal export PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLaporanNetProduk1ActionPerformed

    private void btnLaporanStockActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            List<ProductWithStocks> data = productService.getAllProductsWithStocks();

            Map<String, Object> params = new HashMap<>();
            params.put("tanggalCetak",
                DateTimeFormatter.ofPattern("d MMMM yyyy", Locale.of("id", "ID"))
                    .format(LocalDate.now()));

            InputStream jrxml = getClass().getResourceAsStream("/reports/laporan_stok.jrxml");
            if (jrxml == null) {
                JOptionPane.showMessageDialog(this,
                    "Template JRXML tidak ditemukan di classpath (/reports/laporan_stok.jrxml)");
                return;
            }

            JasperReport report = JasperCompileManager.compileReport(jrxml);
            JasperPrint print = JasperFillManager.fillReport(report, params,
                new JRBeanCollectionDataSource(data));

            String fileName = "laporan_stok.pdf";
            String outPath = reportsPath(fileName);
            JasperExportManager.exportReportToPdfFile(print, outPath);
            openPdf(outPath);

            JOptionPane.showMessageDialog(this, "PDF tersimpan di:\n" + outPath);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal export PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnLaporanCustomerActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            List<CustomerSummary> data = customerService.getAllCustomerSummaries();

            Map<String, Object> params = new HashMap<>();
            params.put("tanggalCetak",
                DateTimeFormatter.ofPattern("d MMMM yyyy", Locale.of("id", "ID"))
                    .format(LocalDate.now()));

            InputStream jrxml = getClass().getResourceAsStream("/reports/laporan_customer.jrxml");
            if (jrxml == null) {
                JOptionPane.showMessageDialog(this,
                    "Template JRXML tidak ditemukan di classpath (/reports/laporan_customer.jrxml)");
                return;
            }

            JasperReport report = JasperCompileManager.compileReport(jrxml);
            JasperPrint print = JasperFillManager.fillReport(report, params,
                new JRBeanCollectionDataSource(data));

            String fileName = "laporan_customer.pdf";
            String outPath = reportsPath(fileName);
            JasperExportManager.exportReportToPdfFile(print, outPath);
            openPdf(outPath);

            JOptionPane.showMessageDialog(this, "PDF tersimpan di:\n" + outPath);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Gagal export PDF: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        MainFrame mf = new MainFrame();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frame_print(mf).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaporanCustomer;
    private javax.swing.JButton btnLaporanNetProduk;
    private javax.swing.JButton btnLaporanNetProduk1;
    private javax.swing.JButton btnLaporanStock;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
