package com.mycompany.buat_apk.frames;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.ArrayList;
import java.util.List;

import com.mycompany.buat_apk.domains.entities.categories.Category;
import com.mycompany.buat_apk.domains.entities.products.CreateProduct;
import com.mycompany.buat_apk.domains.entities.products.ProductWithStocks;
import com.mycompany.buat_apk.domains.frames.ComboCategory;
import com.mycompany.buat_apk.registry.AppContextRegistry;
import com.mycompany.buat_apk.registry.ServiceRegistry;
import com.mycompany.buat_apk.services.CategoryService;
import com.mycompany.buat_apk.services.ProductService;

/**
 *
 * @author najwa amanda
 */
public class frame_produk extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frame_produk.class.getName());
    private java.io.File photo = null;

    private MainFrame parent;

    private String name;
    private String description;
    private int stock;
    private Long price;
    private Long category_id;

    private AppContextRegistry context;

    private final ProductService productService;
    private final CategoryService categoryService;

    /**
     * Creates new form frame_produk
     */
    public frame_produk(MainFrame parent) {
        this.parent = parent;

        ServiceRegistry serviceRegistry = ServiceRegistry.getInstance();

        this.productService = serviceRegistry.productService;
        this.categoryService = serviceRegistry.categoryService;

        AppContextRegistry context = AppContextRegistry.getInstance();
        this.context = context;
        
        for (ProductWithStocks e : this.productService.getAllProductsWithStocks()) {
           System.out.println(e.getImageFile().getAbsolutePath()); 
        }

        initComponents();

        loadCategories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        stockField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descField = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        categoryField = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        photoField = new javax.swing.JLabel();
        uploadFileButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tambah Produk Baru");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama Produk");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Deskripsi");

        descField.setColumns(20);
        descField.setRows(5);
        jScrollPane1.setViewportView(descField);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Kategori");

        saveButton.setBackground(new java.awt.Color(0, 0, 153));
        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Simpan Produk");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        cancelButton.setBackground(new java.awt.Color(255, 51, 51));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Batal");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        photoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        uploadFileButton.setText("Choose image");
        uploadFileButton.addActionListener(this::uploadFileButtonActionPerformed);

        jLabel7.setText("Isi informasi produk yang ingin ditambahkan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Informasi Produk");

        backButton.setBackground(new java.awt.Color(246, 246, 246));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButton.setText("<");
        backButton.setBorderPainted(false);
        backButton.addActionListener(this::backButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(photoField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(uploadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50))))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cancelButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(saveButton))
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(categoryField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameField)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(91, 91, 91)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(stockField))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(photoField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uploadFileButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        clearForm();
    }//GEN-LAST:event_cancelButtonActionPerformed


    private void clearForm() {
        nameField.setText("");
        priceField.setText("");
        stockField.setText("");
        descField.setText("");

        clearImage();

        this.name = "";
        this.description = "";
        this.category_id = null;
        this.photo = null;
        this.price = null;
        this.stock = 0;
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {

//GEN-FIRST:event_saveButtonActionPerformed
        String name = nameField.getText();
        String desc = nameField.getText();

        if (name.equals("") || desc.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please enter the correct name and description.", 
                    "Input Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);

            return;
        }

        this.name = name;
        this.description = desc;

        ComboCategory selectedCategory = (ComboCategory) categoryField.getSelectedItem();

        if(selectedCategory == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please input the right category.", 
                    "Input Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.category_id = selectedCategory.id;

        try {
            String stockText = stockField.getText();
            String priceText = priceField.getText();

            int stock = Integer.parseInt(stockText);
            Long price = Long.parseLong(priceText);

            if (stock < 0 || price < 0) {
                throw new IllegalArgumentException("Values cannot be negative.");
            }


            this.stock = stock;
            this.price = price;
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Please enter valid numbers for Stock and Price.", 
                    "Input Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);

            return;

        } catch (IllegalArgumentException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    e.getMessage(), 
                    "Input Error", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            if (this.photo != null) {
                java.io.File targetDir = new java.io.File("storage/images");
                if (!targetDir.exists()) targetDir.mkdirs();

                java.io.File targetFile = new java.io.File(targetDir, this.photo.getName());

                java.nio.file.Files.copy(
                        this.photo.toPath(), 
                        targetFile.toPath(), 
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING
                        );

                System.out.println("Image saved to: " + targetFile.getPath());
            }


        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error saving: " + e.getMessage());
            return;
        }

        CreateProduct createProductData = new CreateProduct();
        createProductData.setName(this.name);
        createProductData.setImage(this.photo.getName());
        createProductData.setQuantity(this.stock);
        createProductData.setCategoryId(this.category_id);
        createProductData.setDescription(this.description);
        createProductData.setPrice(this.price);

        System.out.println("name: " + this.name);
        System.out.println("description: " + this.description);
        System.out.print("stock: ");
        System.out.println(this.stock);
        System.out.print("price: ");
        System.out.println(this.price);
        System.out.print("category_id: ");
        System.out.println(this.category_id);
        System.out.print("photo: ");
        System.out.println(this.photo.getName());

        this.productService.createProduct(this.context.getActiveUser().getId(), createProductData);


        clearForm();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void uploadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFileButtonActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();

        if (fileChooser.showDialog(this, "This file!") != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        this.photo = fileChooser.getSelectedFile();
        displayImage(this.photo.getAbsolutePath());




    }//GEN-LAST:event_uploadFileButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.parent.goTo("PRODUCT_LIST");
    }//GEN-LAST:event_backButtonActionPerformed
    
    private void displayImage(String path) {
        try {
            int width = photoField.getWidth();
            int height = photoField.getHeight();

            if (width == 0 || height == 0) {
                width = 150;
                height = 150;
            }

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);

            java.awt.Image img = icon.getImage();
            java.awt.Image scaledImg = img.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);

            photoField.setIcon(new javax.swing.ImageIcon(scaledImg));

            photoField.repaint();
            photoField.revalidate();

        } catch (Exception e) {
            System.err.println("Error displaying image: " + e.getMessage());
        }
    }

    private void clearImage() {
        photoField.setIcon(null);

        this.photo = null;
        photoField.repaint();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        MainFrame mf = new MainFrame();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frame_produk(mf).setVisible(true));
    }

    public void loadCategories() {
        try {
            List<Category> categoryList = this.categoryService.getAllCategories();

            List<ComboCategory> comboCategoryList = new ArrayList<>();

            for (Category c : categoryList) {
                comboCategoryList.add(new ComboCategory(c.getId(), c.getName())); 
            }

            ComboCategory[] comboCategoryArray = comboCategoryList.toArray(new ComboCategory[0]);

            categoryField.setModel(new javax.swing.DefaultComboBoxModel<>(comboCategoryArray));

        } catch (Exception e) {
            // Standard error handling for Jakarta-based SWE projects
            System.err.println("Error loading categories: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error: Could not retrieve categories.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<ComboCategory> categoryField;
    private javax.swing.JTextArea descField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel photoField;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stockField;
    private javax.swing.JButton uploadFileButton;
    // End of variables declaration//GEN-END:variables
}
